# Generated by Django 4.2.3 on 2023-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('deal_url', models.CharField(max_length=500)),
                ('img_url', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
