# Generated by Django 4.2.3 on 2023-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0002_alter_deals_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deals_info',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
